export DIRENV_BASH=/bin/bash
eval "$(direnv hook $SHELL)"

fpath=( "$HOME/.dotfiles/zsh/.zfunctions" $fpath )
zstyle ':completion:*' menu select

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey '^[[Z' reverse-menu-complete
bindkey "^[[3~" delete-char

autoload -U promptinit && promptinit
autoload -U compinit && compinit
setopt correct_all
setopt menu_complete
setopt interactive_comments
prompt pure

autoload colors;
colors;

export PATH="/usr/local/bin":"/usr/local/sbin":"/Users/$USER/.gem/ruby/2.0.0/bin":"/usr/local/heroku/bin":$PATH
export CLICOLOR=1
export LSCOLORS="Exfxcxdxbxegedabagacad"
export EDITOR="vim"
export LC_ALL="en_US.UTF-8"
export GREP_OPTIONS='--color=auto'

alias c='clear'
alias passgen="python3 -c \"import random, string; print(''.join(random.choice(string.ascii_letters + string.digits) for _ in range(20)))\""
alias wget='wget --content-disposition'
alias ls="ls -CF"
alias l="ls -CF"
alias ipy="ipython"
alias ip="curl http://checkip.amazonaws.com/"
alias dir="ls -lAhGp"
alias serve="python -m SimpleHTTPServer 8080"
alias strings="strings -a"
alias v="vim"
alias ccat="pygmentize -g"
alias binja='open -a "Binary Ninja.app"'
alias zipcrypt=zipcloak
if type "ipython" > /dev/null; then
    alias py="ipython"
fi
if type "nvim" > /dev/null; then
    alias vim="nvim"
fi
alias tmpsql='docker run --rm --name=mysql --env="MYSQL_ROOT_PASSWORD=password" -p127.0.0.1:3306:3306 mysql:5.7'
alias tmps3='docker run -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" --rm -p 9000:9000 minio/minio server /data'
alias tmppg='docker run --rm --name=postgres --env="POSTGRES_PASSWORD=password" -p127.0.0.1:5432:5432 postgres'
alias tmpredis='docker run -p 127.0.0.1:6379:6379 --rm --name redis redis'
alias tmpmail='docker run --name=inbucket --rm -p 9090:9000 -p 2500:2500 -p 1100:1100 jhillyerd/inbucket:stable'
alias ssh_actual='command ssh'
alias remove_dsstore='find . -name ".DS_Store" -type f -delete'
alias docker-stop-all='docker stop $(docker ps -aq); docker service rm $(docker service ls --format="{{.Name}}")'
alias docker-nuke='docker stop $(docker ps -aq); docker service rm $(docker service ls --format="{{.Name}}"); docker rm $(docker ps -aq)'
alias ubuntu='docker run --rm -it -v `pwd`:/home ubuntu:20.04 bash'

eval `ssh-agent` > /dev/null;
source $(which virtualenvwrapper_lazy.sh);

up() { local p= i=${1:-1}; while (( i-- )); do p+=../; done; cd "$p$2" && pwd; }

ssh() {
    if ! [ -x "$(command -v mosh)" ]; then
        echo "mosh client not found."
        command ssh "$@"
    else
        echo "Found mosh client."
        command mosh "$@"
        [[ $? -ne 0 ]] && (echo "mosh server not found" ; command ssh "$@")
    fi
}

zipfix() {
    # Remove commit hashes from git archives
    local ORIG="$@"
    local FOLDER="$(echo $ORIG | awk '{split($0,a,"."); print a[1]}')"
    local TARGET=`echo $ORIG | awk -F'-' '{$(NF--)=""; OFS="-"; print}'`
    local TARGET=${TARGET%?}
    local TARGET_FOLDER=$TARGET
    TARGET=$TARGET.zip
    echo $TARGET
    echo $TARGET_FOLDER
    echo $FOLDER
    echo $ORIG
    unzip $ORIG
    mv $FOLDER $TARGET_FOLDER
    zip -r $TARGET $TARGET_FOLDER
    rm -rf $TARGET_FOLDER
}
